### PR TITLE
Issue 85 setting ldo flag

### PR DESCRIPTION
**Pull request by torntrousers**
As discussed in https://github.com/sandeepmistry/arduino-LoRa/issues/85 this sets the LDO bit when setting the bandwidth or spreading factor.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
Hi @torntrousers,

Thanks for submitting, could you please re-submit this without the changes from PR #111. Thanks.

**Comment by torntrousers** [comment]
This uses the getSpreadingFactor function that's added in the other pull.

**Comment by torntrousers** [comment]
Is the other pull not going to get merged soon?

**Comment by torntrousers** [comment]
Interesting to see how Semtech does it - https://github.com/Lora-net/LoRaMac-node/blob/master/src/radio/sx1276/sx1276.c#L650-#L658 - perhaps its better to just hard code the ranges like that?

**Comment by sandeepmistry** [comment]
@torntrousers could you please rebase this, PR #11 has been merged.

**Comment by sandeepmistry** [comment]
> Interesting to see how Semtech does it - https://github.com/Lora-net/LoRaMac-node/blob/master/src/radio/sx1276/sx1276.c#L650-#L658 - perhaps its better to just hard code the ranges like that?

@torntrousers sounds good to me, that looks simpler ...

**Comment by torntrousers** [comment]
I don't think the simple calculation is correct so I've put the code back to the previous approach. 
This sets LDO on/off as the following: 
bw: 7800, sf: 6, ldoOn: 0
bw: 10400, sf: 6, ldoOn: 0
bw: 15600, sf: 6, ldoOn: 0
bw: 20800, sf: 6, ldoOn: 0
bw: 31250, sf: 6, ldoOn: 0
bw: 41700, sf: 6, ldoOn: 0
bw: 62500, sf: 6, ldoOn: 0
bw: 125000, sf: 6, ldoOn: 0
bw: 250000, sf: 6, ldoOn: 0
bw: 500000, sf: 6, ldoOn: 0
bw: 500000, sf: 7, ldoOn: 0
bw: 7800, sf: 7, ldoOn: 0
bw: 10400, sf: 7, ldoOn: 0
bw: 15600, sf: 7, ldoOn: 0
bw: 20800, sf: 7, ldoOn: 0
bw: 31250, sf: 7, ldoOn: 0
bw: 41700, sf: 7, ldoOn: 0
bw: 62500, sf: 7, ldoOn: 0
bw: 125000, sf: 7, ldoOn: 0
bw: 250000, sf: 7, ldoOn: 0
bw: 500000, sf: 7, ldoOn: 0
bw: 500000, sf: 8, ldoOn: 0
bw: 7800, sf: 8, ldoOn: 1
bw: 10400, sf: 8, ldoOn: 1
bw: 15600, sf: 8, ldoOn: 0
bw: 20800, sf: 8, ldoOn: 0
bw: 31250, sf: 8, ldoOn: 0
bw: 41700, sf: 8, ldoOn: 0
bw: 62500, sf: 8, ldoOn: 0
bw: 125000, sf: 8, ldoOn: 0
bw: 250000, sf: 8, ldoOn: 0
bw: 500000, sf: 8, ldoOn: 0
bw: 500000, sf: 9, ldoOn: 0
bw: 7800, sf: 9, ldoOn: 1
bw: 10400, sf: 9, ldoOn: 1
bw: 15600, sf: 9, ldoOn: 1
bw: 20800, sf: 9, ldoOn: 1
bw: 31250, sf: 9, ldoOn: 0
bw: 41700, sf: 9, ldoOn: 0
bw: 62500, sf: 9, ldoOn: 0
bw: 125000, sf: 9, ldoOn: 0
bw: 250000, sf: 9, ldoOn: 0
bw: 500000, sf: 9, ldoOn: 0
bw: 500000, sf: 10, ldoOn: 0
bw: 7800, sf: 10, ldoOn: 1
bw: 10400, sf: 10, ldoOn: 1
bw: 15600, sf: 10, ldoOn: 1
bw: 20800, sf: 10, ldoOn: 1
bw: 31250, sf: 10, ldoOn: 1
bw: 41700, sf: 10, ldoOn: 1
bw: 62500, sf: 10, ldoOn: 0
bw: 125000, sf: 10, ldoOn: 0
bw: 250000, sf: 10, ldoOn: 0
bw: 500000, sf: 10, ldoOn: 0
bw: 500000, sf: 11, ldoOn: 0
bw: 7800, sf: 11, ldoOn: 1
bw: 10400, sf: 11, ldoOn: 1
bw: 15600, sf: 11, ldoOn: 1
bw: 20800, sf: 11, ldoOn: 1
bw: 31250, sf: 11, ldoOn: 1
bw: 41700, sf: 11, ldoOn: 1
bw: 62500, sf: 11, ldoOn: 1
bw: 125000, sf: 11, ldoOn: 0
bw: 250000, sf: 11, ldoOn: 0
bw: 500000, sf: 11, ldoOn: 0
bw: 500000, sf: 12, ldoOn: 0
bw: 7800, sf: 12, ldoOn: 1
bw: 10400, sf: 12, ldoOn: 1
bw: 15600, sf: 12, ldoOn: 1
bw: 20800, sf: 12, ldoOn: 1
bw: 31250, sf: 12, ldoOn: 1
bw: 41700, sf: 12, ldoOn: 1
bw: 62500, sf: 12, ldoOn: 1
bw: 125000, sf: 12, ldoOn: 1
bw: 250000, sf: 12, ldoOn: 0
bw: 500000, sf: 12, ldoOn: 0
bw: 500000, sf: 12, ldoOn: 0
bw: 7800, sf: 12, ldoOn: 1
bw: 10400, sf: 12, ldoOn: 1
bw: 15600, sf: 12, ldoOn: 1
bw: 20800, sf: 12, ldoOn: 1
bw: 31250, sf: 12, ldoOn: 1
bw: 41700, sf: 12, ldoOn: 1
bw: 62500, sf: 12, ldoOn: 1
bw: 125000, sf: 12, ldoOn: 1
bw: 250000, sf: 12, ldoOn: 0
bw: 500000, sf: 12, ldoOn: 0

**Comment by torntrousers** [comment]
I've done a bit of testing of this interacting with the Radiohead library using LDO on and off at different spreading factors and bandwidths and it seems to work as I expect. What other testing or could it be merged do you think?

**Comment by halukmy** [comment]
@torntrousers  what is best rssi power and long distance config you prefer? for 1278

**Comment by torntrousers** [comment]
@halukmy I think Stuart who raised https://github.com/sandeepmistry/arduino-LoRa/issues/85 is the best one to answer those type of questions, or checkout his website for lots of useful info - http://www.loratracker.uk/

**Comment by torntrousers** [comment]
So WDYT? Could this get merged?

**Comment by sandeepmistry** [comment]
@torntrousers the changes look ok to me code wise, however I won't be able to test them for a few weeks.

@morganrallen @universam1 @wero1414 @LoRaTracker do you have any feedback on these changes?

**Comment by sandeepmistry** [comment]
@torntrousers thanks for being patient, I'll release a new version in a few minutes ...

**Comment by torntrousers** [comment]
Cool, thanks.

**Pull request merged**
